from typing import Any

import torch

def hashmap_insert_cuda(*args: Any, **kwargs: Any) -> Any: ...
def hashmap_lookup_cuda(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def hashmap_insert_3d_cuda(*args: Any, **kwargs: Any) -> Any: ...
def hashmap_lookup_3d_cuda(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def hashmap_insert_3d_idx_as_val_cuda(*args: Any, **kwargs: Any) -> Any: ...
def mesh_to_flexible_dual_grid_cpu(
    vertices: torch.Tensor,
    faces: torch.Tensor,
    voxel_size: torch.Tensor,
    grid_range: torch.Tensor,
    face_weight: float,
    boundary_weight: float,
    regularization_weight: float,
    timing: bool,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
def mesh_to_flexible_dual_grid_cuda(
    vertices: torch.Tensor,
    faces: torch.Tensor,
    voxel_size: torch.Tensor,
    grid_range: torch.Tensor,
    face_weight: float,
    boundary_weight: float,
    regularization_weight: float,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
def textured_mesh_to_volumetric_attr_cpu(*args: Any, **kwargs: Any) -> tuple[torch.Tensor, ...]: ...
def z_order_encode_cpu(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor: ...
def z_order_decode_cpu(code: torch.Tensor) -> torch.Tensor: ...
def hilbert_encode_cpu(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor: ...
def hilbert_decode_cpu(code: torch.Tensor) -> torch.Tensor: ...
def z_order_encode_cuda(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor: ...
def z_order_decode_cuda(code: torch.Tensor) -> torch.Tensor: ...
def hilbert_encode_cuda(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor: ...
def hilbert_decode_cuda(code: torch.Tensor) -> torch.Tensor: ...
def encode_sparse_voxel_octree_cpu(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def decode_sparse_voxel_octree_cpu(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def encode_sparse_voxel_octree_attr_parent_cpu(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def decode_sparse_voxel_octree_attr_parent_cpu(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def encode_sparse_voxel_octree_attr_neighbor_cpu(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def decode_sparse_voxel_octree_attr_neighbor_cpu(*args: Any, **kwargs: Any) -> torch.Tensor: ...
def rasterize_voxels_cuda(*args: Any, **kwargs: Any) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
